[package]
name = "jmespath"
version = "0.0.1"
authors = ["Michael Dowling <mtdowling@gmail.com>"]
license = "MIT"
build = "build.rs"

[dependencies]
serde_json = "^0.6"

[build-dependencies]
serde_json = "^0.6"
slug = "0.1.1"
