[package]
name = "jmespath-cli"
version = "0.0.1"
authors = ["Michael Dowling <mtdowling@gmail.com>"]
license = "MIT"

[[bin]]
name = "jp"

[dependencies]
serde = "^0.8"
serde_json = "^0.8"
clap = "^2.4"

[dependencies.jmespath]
path = ".."
version = "*"
