[package]
name = "jmespath-cli"
version = "0.0.2"
authors = ["Michael Dowling <mtdowling@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
serde = "1"
serde_json = "1"
clap = "^2.4"

[dependencies.jmespath]
path = ".."
version = "*"
