[package]
name = "jp"
version = "0.0.1"
authors = ["Michael Dowling <mtdowling@gmail.com>"]
license = "MIT"

[dependencies]
serde = "^0.6"
serde_json = "^0.6"
clap = "1"

[dependencies.jmespath]
path = ".."
version = "*"
